### ISSUE TITLE
Hello,is it can use in Internet ipv6?

### ISSUE THREAD

**Issue by tamperMonkeyZQ** [beli-sk/pywake#1]
Hello,can it use in Internet(ipv6)?
Looking forward to your reply

**Comment by beli-sk** [comment]
Hi,
in theory it may be possible, but you need to make sure that the packet can reach the target device even when it's not responding to usual network traffic, like the neighbor discovery protocol in the case of IPv6.
You could try to set up static neighbor entry on your router for the target device, so it knows which MAC address belongs to that IP address without needing to ask the target device:
http://www.iitk.ac.in/LDP/HOWTO/Linux+IPv6-HOWTO/ch08s02.html

For more pointers about Wake-On-Lan protocol checkout it's Wikipedia article https://en.wikipedia.org/wiki/Wake-on-LAN

Hope that helps.
